#!/bin/bash
HEADS=${@:1:$(($# - 1))}
TAIL=${@:$#}

# echo ${HEADS}
# echo ${TAIL}

racket /plumb/plumb.rkt \
  ${HEADS} \
  --config /plumb/client-config/docker.yaml \
  --mqtt-host localhost \
  --mqtt-port 8338 \
  --mqtt-channel plumbing \
  ${TAIL}
